dockerproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dockers.urls')),
]

dockers/urls.py
# urls.py
from django.urls import path
from .views import FileUploadView, DocketListView, create_docket_entry, get_purchase_order_description, get_purchase_orders, CreatedDocketsListView

urlpatterns = [
    path('', FileUploadView.as_view(), name='file_upload'),
    path('dockets/', DocketListView.as_view(), name='docket_list'),
    path('create_docket_entry/', create_docket_entry, name='create_docket_entry'),
    path('get_purchase_orders/', get_purchase_orders, name='get_purchase_orders'),
    path('get_purchase_order_description/', get_purchase_order_description, name='get_purchase_order_description'),
    path('created_dockets/', CreatedDocketsListView.as_view(), name='created_dockets_list'),
]

dockers/models.py
from django.db import models

class Supplier(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

class PurchaseOrder(models.Model):
    supplier = models.ForeignKey(Supplier, on_delete=models.CASCADE)
    number = models.CharField(max_length=255)
    description = models.TextField()

    def __str__(self):
        return f'{self.number}'
class Docket(models.Model):
    record_type = models.CharField(max_length=255)
    chg = models.CharField(max_length=255, blank=True, null=True)
    com = models.CharField(max_length=255, blank=True, null=True)
    docket_type = models.CharField(max_length=255, blank=True, null=True)
    confirmation = models.CharField(max_length=255, blank=True, null=True)
    order_date = models.DateField()
    buyer = models.CharField(max_length=255)
    account_number = models.CharField(max_length=255)
    currency = models.CharField(max_length=3)
    item = models.CharField(max_length=255)
    commodity_code = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    quantity = models.FloatField()
    unit = models.CharField(max_length=10)
    order_value = models.FloatField()
    amount_invoiced = models.FloatField()
    wbs_code = models.CharField(max_length=255, blank=True, null=True)
    contract = models.CharField(max_length=255)
    remarks = models.CharField(max_length=255, blank=True, null=True)
    supplier = models.ForeignKey(Supplier, on_delete=models.CASCADE)
    po_number = models.ForeignKey(PurchaseOrder, on_delete=models.CASCADE)

    def __str__(self):
        return self.po_number

class DocketEntry(models.Model):
    name = models.CharField(max_length=255)
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()
    hours_worked = models.FloatField()
    rate_per_hour = models.FloatField()
    supplier = models.ForeignKey(Supplier, on_delete=models.CASCADE)
    purchase_order = models.ForeignKey(PurchaseOrder, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


dockers/forms.py
from django import forms
from .models import DocketEntry

class UploadFileForm(forms.Form):
    file = forms.FileField()

class DocketEntryForm(forms.ModelForm):
    class Meta:
        model = DocketEntry
        fields = ['name', 'start_time', 'end_time', 'hours_worked', 'rate_per_hour', 'supplier', 'purchase_order']
        widgets = {
            'start_time': forms.TextInput(attrs={'type': 'datetime-local'}),
            'end_time': forms.TextInput(attrs={'type': 'datetime-local'}),
        }

        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            self.fields[
                'purchase_order'].queryset = PurchaseOrder.objects.none()  # Initially, no options in the purchase order dropdown
            if 'supplier' in self.data:
                try:
                    supplier_id = int(self.data.get('supplier'))
                    self.fields['purchase_order'].queryset = PurchaseOrder.objects.filter(supplier_id=supplier_id)
                except (ValueError, TypeError):
                    pass  # Handle the case when supplier ID is not valid or not provided
            elif self.instance.pk:
                self.fields['purchase_order'].queryset = self.instance.supplier.purchaseorder_set.all()


dockers/views.py
import pandas as pd
from django.http import JsonResponse
from django.views.generic import TemplateView, ListView
from django.shortcuts import redirect, render
from django.db.models import Prefetch
from .forms import UploadFileForm, DocketEntryForm
from .models import Docket,Supplier, PurchaseOrder, DocketEntry

class FileUploadView(TemplateView):
    template_name = 'upload_report.html'  # Specify the path to your template

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = UploadFileForm()  # Pass an instance of the form to the template
        return context

    def handle_supplier_purchase_order(self, supplier_name, purchase_order_number):
        supplier, created = Supplier.objects.get_or_create(name=supplier_name)
        purchase_order, created = PurchaseOrder.objects.get_or_create(
            supplier=supplier,
            number=purchase_order_number,
            defaults={'description': 'Default Description'}  # Provide a default description if necessary
        )
        return supplier, purchase_order

    def post(self, request, *args, **kwargs):
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            # Handle the uploaded files here (save them, process them, etc.)
            # Access the files using form.cleaned_data['file_field']
            Docket.objects.all().delete()
            DocketEntry.objects.all().delete()
            uploaded_file = request.FILES['file']

            if uploaded_file.name.endswith('.xls') or uploaded_file.name.endswith('.xlsx'):
                # Read the Excel file using pandas
                df = pd.read_excel(uploaded_file)
                df = df.ffill()

                # Iterate through DataFrame and save data to Docket model
                for index, row in df.iterrows():
                    supplier_name = row['Supplier']  # Assuming the column name in Excel for supplier
                    purchase_order_number = row[
                        'PO Number']  # Assuming the column name in Excel for purchase order

                    supplier, purchase_order = self.handle_supplier_purchase_order(supplier_name, purchase_order_number)
                    docket = Docket.objects.create(
                        record_type=row['Record Type'],
                        po_number=purchase_order,
                        chg=row['Chg'],
                        com=row['Com'],
                        docket_type=row['Type'],
                        confirmation=row['Conf'],
                        order_date=row['Order Date'],
                        buyer=row['Buyer'],
                        account_number=row['Account Number'],
                        supplier=supplier,
                        currency=row['Curr'],
                        item=row['Item'],
                        commodity_code=row['Commodity Code'],
                        description=row['Description'],
                        quantity=row['Qty'],
                        unit=row['Un'],
                        order_value=row['Order Value'],
                        amount_invoiced=row['Amount Invoiced'],
                        wbs_code=row['WBS Code'],
                        contract=row['Contract'],
                        remarks=row['Remarks']
                    )

                return redirect('docket_list')
        return self.render_to_response(self.get_context_data(form=form))


class DocketListView(ListView):
    model = Docket
    template_name = 'docket_table.html'  # Specify the template name
    context_object_name = 'dockets'
    paginate_by = 50  # Number of items per page

    def get_queryset(self):
        # You can customize the queryset if needed, e.g., ordering
        return Docket.objects.all().order_by('id')


def get_purchase_orders(request):
    supplier_id = request.GET.get('supplier_id')
    purchase_orders = PurchaseOrder.objects.filter(supplier_id=supplier_id)
    data = [{'id': po.id, 'name': po.number} for po in purchase_orders]
    return JsonResponse({'purchase_orders': data})

def create_docket_entry(request):
    if request.method == 'POST':
        form = DocketEntryForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('created_dockets_list')
    else:
        form = DocketEntryForm()

    return render(request, 'create_docket_entry.html', {'form': form})

def get_purchase_order_description(request):
    purchase_order_id = request.GET.get('purchase_order_id')
    try:
        descriptions = Docket.objects.filter(po_number=purchase_order_id).values('description').distinct()
        descriptions_list = [entry['description'] for entry in descriptions]
        if not descriptions_list:
            descriptions_list = ['Description not found']  # Default description if no descriptions found
    except Docket.DoesNotExist:
        descriptions_list = ['Description not found']  # Default description if PO is not found

    return JsonResponse({'descriptions': descriptions_list})

class CreatedDocketsListView(ListView):
    model = DocketEntry
    template_name = 'created_dockets_list.html'  # Specify the template name
    context_object_name = 'created_dockets'

    def get_queryset(self):
        dockets_with_descriptions = Docket.objects.all().only('id', 'description')
        prefetch_dockets = Prefetch('purchase_order__docket_set', queryset=dockets_with_descriptions, to_attr='dockets')

        return DocketEntry.objects.all().prefetch_related(prefetch_dockets).order_by('-id')


dockers/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Docket Management{% endblock %}</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="#">Docket Management</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item {% block file_upload_active %}{% endblock %}">
                    <a class="nav-link" href="{% url 'file_upload' %}">Upload File</a>
                </li>
                <li class="nav-item {% block docket_list_active %}{% endblock %}">
                    <a class="nav-link" href="{% url 'docket_list' %}">Docket List</a>
                </li>
                <li class="nav-item {% block create_docket_entry_active %}{% endblock %}">
                    <a class="nav-link" href="{% url 'create_docket_entry' %}">Create Docket Entry</a>
                </li>
                <li class="nav-item {% block created_dockets_list_active %}{% endblock %}">
                    <a class="nav-link" href="{% url 'created_dockets_list' %}">Created Dockets</a>
                </li>
            </ul>
        </div>
    </nav>

    <div class="container mt-4">
        {% block content %}
        {% endblock %}
    </div>

    <!-- Bootstrap JS and jQuery -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</body>
</html>

dockers/templates/create_docket_entry.html
{% extends 'base.html' %}

{% block title %}Create Docket Entry{% endblock %}

{% block create_docket_entry_active %}active{% endblock %}

{% block content %}
    <h2>Create Docket Entry</h2>
    <form method="post" class="form">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="form-group">
            <div id="purchase-order-description" class="mt-2"></div>
        </div>
        <input type="submit" value="Create Docket Entry" class="btn btn-primary">
    </form>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/js/bootstrap-datetimepicker.min.js"></script>
<script>
        // Initialize DateTimePicker for start_time and end_time fields
        $(document).ready(function(){
            $('#id_start_time').datetimepicker({
                format: 'YYYY-MM-DDTHH:mm:ss',
                useCurrent: false,
                sideBySide: true
            });


            $('#id_end_time').datetimepicker({
                format: 'YYYY-MM-DDTHH:mm:ss',
                useCurrent: false,
                sideBySide: true
            });
        });
    </script>
<script>
    $(document).ready(function() {

    $('#id_supplier').change(function() {
        var supplierId = $(this).val();
        $.ajax({
            url: '/get_purchase_orders/',
            data: {'supplier_id': supplierId},
            dataType: 'json',
            success: function(data) {
                $('#id_purchase_order').empty();
                $('#id_purchase_order').append($('<option>', {
        value: '----------',
        text: '----------'
    }));
                $.each(data.purchase_orders, function(index, po) {
                    $('#id_purchase_order').append($('<option>', {
                        value: po.id,
                        text: po.name
                    }));
                });
            }
        });
    });
});

</script>
<script>
    $(document).ready(function() {
    $('#id_purchase_order').change(function() {
        var purchaseOrderId = $(this).val();
        if (purchaseOrderId !== '----------') {
                $.ajax({
                    url: '/get_purchase_order_description/',
                    data: {'purchase_order_id': purchaseOrderId},
                    dataType: 'json',
                    success: function(data) {
                        var descriptionHtml = '';
                        $.each(data.descriptions, function(index, description) {
                            descriptionHtml += '<p>' + description + '</p>';
                        });
                        $('#purchase-order-description').html(descriptionHtml);
                    }
                });
            } else {
                $('#purchase-order-description').html('');  // Clear description if the default dash is selected
            }
    });
});

</script>

{% endblock %}

dockers/templates/created_dockets_list.html
{% extends 'base.html' %}

{% block title %}Created Dockets List{% endblock %}

{% block created_dockets_active %}active{% endblock %}

{% block content %}
    <h2>Created Dockets</h2>
    <table class="table table-striped custom-table">
        <thead class="thead-dark">
            <tr>
                <th>Name</th>
                <th>Start Time</th>
                <th>End Time</th>
                <th>Hours Worked</th>
                <th>Rate Per Hour</th>
                <th>Supplier</th>
                <th>Purchase Order</th>
                <th>Description</th>
            </tr>
        </thead>
        <tbody>
            {% for created_docket in created_dockets %}
                <tr>
                    <td>{{ created_docket.name }}</td>
                    <td>{{ created_docket.start_time }}</td>
                    <td>{{ created_docket.end_time }}</td>
                    <td>{{ created_docket.hours_worked }}</td>
                    <td>{{ created_docket.rate_per_hour }}</td>
                    <td>{{ created_docket.supplier }}</td>
                    <td>{{ created_docket.purchase_order }}</td>
                    <td>
                        {% for docket in created_docket.purchase_order.dockets %}
                            {{ docket.description }}<br>
                        {% empty %}
                            No description available.
                        {% endfor %}
                    </td>
                </tr>
            {% empty %}
                <tr>
                    <td colspan="7">No created dockets available.</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

dockers/templates/docket_table.html
{% extends 'base.html' %}

{% block title %}Docket List{% endblock %}

{% block docket_list_active %}active{% endblock %}

{% block content %}
    <h1>Uploaded Docket Data</h1>
<a class="nav-link" href="{% url 'create_docket_entry' %}">
    <button type="button" class="btn btn-primary">
        Create New Docket Entry
    </button></a>
       <table class="table table-striped custom-table">
            <thead class="thead-dark">
                <tr>
                    <th>PO Number</th>
                    <th>Order Date</th>
                    <th>Buyer</th>
                    <th>Supplier</th>
                    <th>Description</th>
                </tr>
            </thead>
            <tbody>
                {% for docket in dockets %}
                <tr>
                    <td>{{ docket.po_number }}</td>
                    <td>{{ docket.order_date }}</td>
                    <td>{{ docket.buyer }}</td>
                    <td>{{ docket.supplier }}</td>
                    <td>{{ docket.description }}</td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="6">No docket data available.</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
<!-- Pagination controls -->
    <div class="pagination">
        {% if page_obj.has_previous %}
        <a href="?page=1">First</a>
        <a href="?page={{ page_obj.previous_page_number }}">Previous</a>
    {% endif %}
    <span class="current">
        Page {{ page_obj.number }} of {{ paginator.num_pages }}.
    </span>
    {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">Next</a>
        <a href="?page={{ paginator.num_pages }}">Last</a>
    {% endif %}
    </div>
{% endblock %}

dockers/templates/upload_report.html
{% extends 'base.html' %}

{% block title %}Upload File{% endblock %}

{% block file_upload_active %}active{% endblock %}

{% block content %}
    <h2>File Upload Form</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Upload</button>
    </form>
{% endblock %}